---
- name: Installing the NGINX service on Mattermost server
  become: yes
  apt:
    name: nginx
    state: present

- name: Starting NGINX service
  become: yes
  systemd:
    name: nginx
    state: started

- name: Creating configuration file for Mattermost
  become: yes
  template:
    src: matter.j2
    dest: /etc/nginx/sites-available/mattermost
  
- name: Deleting default NGINX config file
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Creating softlink for new configuration file
  become: yes
  file:
    src: /etc/nginx/sites-available/mattermost
    dest: /etc/nginx/sites-enabled/mattermost
    state: link

- name: Restarting the NGINX service
  become: yes
  systemd:
    name: nginx
    state: restarted
